// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scraper} from '../models';

export function GetLatestReleaseAnime():Promise<Array<scraper.LU_Anime>>;

export function GetTrendingAnime():Promise<Array<scraper.T_Anime>>;

export function GetTrendingManga():Promise<Array<scraper.T_Manga>>;

export function GetUpdatedManga():Promise<Array<scraper.LU_Manga>>;

export function Greet(arg1:string):Promise<string>;

export function OpenUrl(arg1:string):Promise<void>;
