// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLatestReleaseAnime() {
  return window['go']['main']['App']['GetLatestReleaseAnime']();
}

export function GetTrendingAnime() {
  return window['go']['main']['App']['GetTrendingAnime']();
}

export function GetTrendingManga() {
  return window['go']['main']['App']['GetTrendingManga']();
}

export function GetUpdatedManga() {
  return window['go']['main']['App']['GetUpdatedManga']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenUrl(arg1) {
  return window['go']['main']['App']['OpenUrl'](arg1);
}
